### ISSUE TITLE
more arguments (color, opacity, suffix)

### ISSUE THREAD

**Issue by agrajaghh** [sebkur/android-res-utils#1]
currently you can just specify the size. But I think color, opacity and suffix are important as well, since they are not the same for the whole project/every file.

**Comment by sebkur** [comment]
Yes, at the moment, this is really specific to what the last paragraph of the [Material Design Guide for Icon Style](http://www.google.com/design/spec/style/icons.html#icons-system-icons) states about icons for light/dark backgrounds. I think it's a good thing to further generalize the script.

**Comment by agrajaghh** [comment]
ty
